# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Taslak(object):
    def setupUi(self, Taslak):
        Taslak.setObjectName("Taslak")
        Taslak.setWindowModality(QtCore.Qt.NonModal)
        Taslak.setEnabled(True)
        Taslak.resize(1624, 931)
        Taslak.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Taslak.setWindowTitle("")
        Taslak.setStyleSheet("")
        Taslak.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Taslak.setAnimated(True)
        Taslak.setDocumentMode(False)
        Taslak.setTabShape(QtWidgets.QTabWidget.Triangular)
        Taslak.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Taslak)
        self.centralwidget.setStyleSheet("/* tw_menu objesinin arka planı */\n"
"#anamanu {\n"
"    background-color: light gray;\n"
"    background-image: url(:/team/icons/team-logo.png);\n"
"    background-size: cover;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tw_menu = QtWidgets.QTabWidget(self.centralwidget)
        self.tw_menu.setEnabled(True)
        self.tw_menu.setGeometry(QtCore.QRect(0, 0, 1561, 871))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tw_menu.setFont(font)
        self.tw_menu.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tw_menu.setStyleSheet("  background-color: light gray;\n"
"\n"
" \n"
"\n"
"")
        self.tw_menu.setIconSize(QtCore.QSize(20, 20))
        self.tw_menu.setObjectName("tw_menu")
        self.anamanu = QtWidgets.QWidget()
        self.anamanu.setStyleSheet(" background-color: rgba(255, 255, 255,255);\n"
"")
        self.anamanu.setObjectName("anamanu")
        self.pb_kac = QtWidgets.QPushButton(self.anamanu)
        self.pb_kac.setGeometry(QtCore.QRect(10, 790, 131, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pb_kac.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_kac.setFont(font)
        self.pb_kac.setStyleSheet("#pushb_kac\n"
"{\n"
"border: solid rgb(37,39,48);\n"
"background:hotpink;\n"
"border-radius:12px;\n"
"}")
        self.pb_kac.setObjectName("pb_kac")
        self.gb_imuInfo = QtWidgets.QGroupBox(self.anamanu)
        self.gb_imuInfo.setGeometry(QtCore.QRect(0, 400, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_imuInfo.setFont(font)
        self.gb_imuInfo.setStyleSheet("")
        self.gb_imuInfo.setObjectName("gb_imuInfo")
        self.gridLayoutWidget = QtWidgets.QWidget(self.gb_imuInfo)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 171, 106))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gl_IMU = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gl_IMU.setContentsMargins(0, 0, 0, 0)
        self.gl_IMU.setObjectName("gl_IMU")
        self.lbl_pitch = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_pitch.setFont(font)
        self.lbl_pitch.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_pitch.setObjectName("lbl_pitch")
        self.gl_IMU.addWidget(self.lbl_pitch, 1, 1, 1, 1)
        self.lbl_yaw = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_yaw.setFont(font)
        self.lbl_yaw.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_yaw.setObjectName("lbl_yaw")
        self.gl_IMU.addWidget(self.lbl_yaw, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gl_IMU.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gl_IMU.addWidget(self.label_5, 2, 0, 1, 1)
        self.lbl_roll = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_roll.setFont(font)
        self.lbl_roll.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_roll.setObjectName("lbl_roll")
        self.gl_IMU.addWidget(self.lbl_roll, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gl_IMU.addWidget(self.label_4, 1, 0, 1, 1)
        self.gb_gpsInfo = QtWidgets.QGroupBox(self.anamanu)
        self.gb_gpsInfo.setGeometry(QtCore.QRect(190, 400, 191, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_gpsInfo.setFont(font)
        self.gb_gpsInfo.setStyleSheet("")
        self.gb_gpsInfo.setObjectName("gb_gpsInfo")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.gb_gpsInfo)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 22, 181, 106))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gl_GPS = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gl_GPS.setContentsMargins(0, 0, 0, 0)
        self.gl_GPS.setObjectName("gl_GPS")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gl_GPS.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gl_GPS.addWidget(self.label_6, 1, 0, 1, 1)
        self.lbl_enlem = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_enlem.setFont(font)
        self.lbl_enlem.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_enlem.setObjectName("lbl_enlem")
        self.gl_GPS.addWidget(self.lbl_enlem, 0, 1, 1, 1)
        self.lbl_irtifa = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_irtifa.setFont(font)
        self.lbl_irtifa.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_irtifa.setObjectName("lbl_irtifa")
        self.gl_GPS.addWidget(self.lbl_irtifa, 2, 1, 1, 1)
        self.lbl_boylam = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_boylam.setFont(font)
        self.lbl_boylam.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_boylam.setObjectName("lbl_boylam")
        self.gl_GPS.addWidget(self.lbl_boylam, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gl_GPS.addWidget(self.label_7, 2, 0, 1, 1)
        self.pb_arm = QtWidgets.QPushButton(self.anamanu)
        self.pb_arm.setGeometry(QtCore.QRect(160, 790, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_arm.sizePolicy().hasHeightForWidth())
        self.pb_arm.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pb_arm.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pb_arm.setFont(font)
        self.pb_arm.setStyleSheet("#pb_arm\n"
"{\n"
"border: solid rgb(37,39,48);\n"
"background:black;\n"
"border-radius:12px;\n"
"}")
        self.pb_arm.setObjectName("pb_arm")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.anamanu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_HUD = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_HUD.setContentsMargins(0, 0, 0, 0)
        self.vl_HUD.setObjectName("vl_HUD")
        self.lbl_kamera = QtWidgets.QLabel(self.anamanu)
        self.lbl_kamera.setGeometry(QtCore.QRect(390, 20, 471, 391))
        self.lbl_kamera.setStyleSheet("border-image: url(:/team/icons/kamera.png);\n"
"background-size: coverset\n"
"")
        self.lbl_kamera.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_kamera.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_kamera.setText("")
        self.lbl_kamera.setScaledContents(True)
        self.lbl_kamera.setWordWrap(False)
        self.lbl_kamera.setObjectName("lbl_kamera")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.anamanu)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(830, 30, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vl_MAP = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vl_MAP.setContentsMargins(0, 0, 0, 0)
        self.vl_MAP.setObjectName("vl_MAP")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.anamanu)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(880, 10, 671, 821))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vl_map = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vl_map.setContentsMargins(0, 0, 0, 0)
        self.vl_map.setObjectName("vl_map")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.anamanu)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 600, 341, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_3)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1222, 1222))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_terminal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_terminal.setMinimumSize(QtCore.QSize(1200, 1200))
        self.lbl_terminal.setStyleSheet("")
        self.lbl_terminal.setText("")
        self.lbl_terminal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_terminal.setObjectName("lbl_terminal")
        self.verticalLayout_2.addWidget(self.lbl_terminal)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.cb_ucus_mod = QtWidgets.QComboBox(self.anamanu)
        self.cb_ucus_mod.setGeometry(QtCore.QRect(10, 540, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        self.cb_ucus_mod.setFont(font)
        self.cb_ucus_mod.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: black;\n"
"    color: white;\n"
"    \n"
"}\n"
"")
        self.cb_ucus_mod.setObjectName("cb_ucus_mod")
        self.cb_ucus_mod.addItem("")
        self.cb_ucus_mod.addItem("")
        self.cb_ucus_mod.addItem("")
        self.cb_ucus_mod.addItem("")
        self.cb_ucus_mod.addItem("")
        self.cb_ucus_mod.addItem("")
        self.gb_teaminfo = QtWidgets.QGroupBox(self.anamanu)
        self.gb_teaminfo.setGeometry(QtCore.QRect(390, 540, 481, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gb_teaminfo.setFont(font)
        self.gb_teaminfo.setStyleSheet("")
        self.gb_teaminfo.setObjectName("gb_teaminfo")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.gb_teaminfo)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 231, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gl_hizBilgi_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gl_hizBilgi_2.setContentsMargins(0, 0, 0, 0)
        self.gl_hizBilgi_2.setObjectName("gl_hizBilgi_2")
        self.lbl_speed_r = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_speed_r.setFont(font)
        self.lbl_speed_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_speed_r.setObjectName("lbl_speed_r")
        self.gl_hizBilgi_2.addWidget(self.lbl_speed_r, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gl_hizBilgi_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.gb_teaminfo)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 80, 231, 141))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gl_IMU_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gl_IMU_2.setContentsMargins(0, 0, 0, 0)
        self.gl_IMU_2.setObjectName("gl_IMU_2")
        self.lbl_pitch_r = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_pitch_r.setFont(font)
        self.lbl_pitch_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_pitch_r.setObjectName("lbl_pitch_r")
        self.gl_IMU_2.addWidget(self.lbl_pitch_r, 1, 1, 1, 1)
        self.lbl_yaw_r = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_yaw_r.setFont(font)
        self.lbl_yaw_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_yaw_r.setObjectName("lbl_yaw_r")
        self.gl_IMU_2.addWidget(self.lbl_yaw_r, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gl_IMU_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gl_IMU_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.lbl_roll_r = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_roll_r.setFont(font)
        self.lbl_roll_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_roll_r.setObjectName("lbl_roll_r")
        self.gl_IMU_2.addWidget(self.lbl_roll_r, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("")
        self.label_22.setObjectName("label_22")
        self.gl_IMU_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.gb_teaminfo)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(250, 20, 231, 101))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gl_GPS_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gl_GPS_2.setContentsMargins(0, 0, 0, 0)
        self.gl_GPS_2.setObjectName("gl_GPS_2")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.gl_GPS_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.gl_GPS_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.lbl_enlem_r = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_enlem_r.setFont(font)
        self.lbl_enlem_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
" \n"
"}\n"
"")
        self.lbl_enlem_r.setObjectName("lbl_enlem_r")
        self.gl_GPS_2.addWidget(self.lbl_enlem_r, 0, 1, 1, 1)
        self.lbl_irtifa_r = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_irtifa_r.setFont(font)
        self.lbl_irtifa_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"\n"
" \n"
"}\n"
"")
        self.lbl_irtifa_r.setObjectName("lbl_irtifa_r")
        self.gl_GPS_2.addWidget(self.lbl_irtifa_r, 2, 1, 1, 1)
        self.lbl_boylam_r = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_boylam_r.setFont(font)
        self.lbl_boylam_r.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
" \n"
"}\n"
"")
        self.lbl_boylam_r.setObjectName("lbl_boylam_r")
        self.gl_GPS_2.addWidget(self.lbl_boylam_r, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.gl_GPS_2.addWidget(self.label_24, 2, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.gb_teaminfo)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(250, 130, 231, 91))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gl_GPS_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gl_GPS_3.setContentsMargins(0, 0, 0, 0)
        self.gl_GPS_3.setObjectName("gl_GPS_3")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.gl_GPS_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("")
        self.label_25.setObjectName("label_25")
        self.gl_GPS_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.lbl_servertime = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_servertime.setFont(font)
        self.lbl_servertime.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
" \n"
"}\n"
"")
        self.lbl_servertime.setObjectName("lbl_servertime")
        self.gl_GPS_3.addWidget(self.lbl_servertime, 1, 1, 1, 1)
        self.lbl_time_dif = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_time_dif.setFont(font)
        self.lbl_time_dif.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
" \n"
"}\n"
"")
        self.lbl_time_dif.setObjectName("lbl_time_dif")
        self.gl_GPS_3.addWidget(self.lbl_time_dif, 0, 1, 1, 1)
        self.pb_mod_onay = QtWidgets.QPushButton(self.anamanu)
        self.pb_mod_onay.setGeometry(QtCore.QRect(200, 540, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_mod_onay.setFont(font)
        self.pb_mod_onay.setStyleSheet("\n"
"QPushButton\n"
" {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}")
        self.pb_mod_onay.setObjectName("pb_mod_onay")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.anamanu)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(400, 430, 211, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gl_hizBilgi = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gl_hizBilgi.setContentsMargins(0, 0, 0, 0)
        self.gl_hizBilgi.setObjectName("gl_hizBilgi")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gl_hizBilgi.addWidget(self.label_10, 0, 0, 1, 1)
        self.lbl_yerhizi = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_yerhizi.setFont(font)
        self.lbl_yerhizi.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_yerhizi.setObjectName("lbl_yerhizi")
        self.gl_hizBilgi.addWidget(self.lbl_yerhizi, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gl_hizBilgi.addWidget(self.label_11, 1, 0, 1, 1)
        self.lbl_havahizi = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_havahizi.setFont(font)
        self.lbl_havahizi.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_havahizi.setObjectName("lbl_havahizi")
        self.gl_hizBilgi.addWidget(self.lbl_havahizi, 1, 1, 1, 1)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.anamanu)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(630, 430, 231, 91))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gl_hizBilgi_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gl_hizBilgi_7.setContentsMargins(0, 0, 0, 0)
        self.gl_hizBilgi_7.setHorizontalSpacing(2)
        self.gl_hizBilgi_7.setObjectName("gl_hizBilgi_7")
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("")
        self.label_58.setObjectName("label_58")
        self.gl_hizBilgi_7.addWidget(self.label_58, 0, 0, 1, 1)
        self.lbl_ucus_mod = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_ucus_mod.setFont(font)
        self.lbl_ucus_mod.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
" \n"
"}\n"
"")
        self.lbl_ucus_mod.setObjectName("lbl_ucus_mod")
        self.gl_hizBilgi_7.addWidget(self.lbl_ucus_mod, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("")
        self.label_59.setObjectName("label_59")
        self.gl_hizBilgi_7.addWidget(self.label_59, 1, 0, 1, 1)
        self.lbl_ucus_zaman = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_ucus_zaman.setFont(font)
        self.lbl_ucus_zaman.setStyleSheet("QLabel {\n"
"    background-color: #4d4d4d;  /* koyu gri */\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"")
        self.lbl_ucus_zaman.setObjectName("lbl_ucus_zaman")
        self.gl_hizBilgi_7.addWidget(self.lbl_ucus_zaman, 1, 1, 1, 1)
        self.pb_kill = QtWidgets.QPushButton(self.anamanu)
        self.pb_kill.setGeometry(QtCore.QRect(356, 600, 31, 28))
        self.pb_kill.setObjectName("pb_kill")
        self.tw_menu.addTab(self.anamanu, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(110, 60, 921, 611))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.verticalLayoutWidget_6)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 896, 586))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_veri = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_veri.setText("")
        self.lbl_veri.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_veri.setObjectName("lbl_veri")
        self.verticalLayout_4.addWidget(self.lbl_veri)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)
        self.tw_menu.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pb_renkmod = QtWidgets.QPushButton(self.tab_2)
        self.pb_renkmod.setGeometry(QtCore.QRect(20, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_renkmod.setFont(font)
        self.pb_renkmod.setStyleSheet("#pb_renkmod\n"
"{\n"
"border: solid rgb(37,39,48);\n"
"background:pink;\n"
"border-radius:12px;\n"
"}")
        self.pb_renkmod.setObjectName("pb_renkmod")
        self.gp_guvenlikonlemleri_2 = QtWidgets.QGroupBox(self.tab_2)
        self.gp_guvenlikonlemleri_2.setGeometry(QtCore.QRect(20, 90, 171, 201))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.gp_guvenlikonlemleri_2.setFont(font)
        self.gp_guvenlikonlemleri_2.setObjectName("gp_guvenlikonlemleri_2")
        self.lbl_maxirtifa_2 = QtWidgets.QLabel(self.gp_guvenlikonlemleri_2)
        self.lbl_maxirtifa_2.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.lbl_maxirtifa_2.setFont(font)
        self.lbl_maxirtifa_2.setObjectName("lbl_maxirtifa_2")
        self.le_maxirtifa_2 = QtWidgets.QLineEdit(self.gp_guvenlikonlemleri_2)
        self.le_maxirtifa_2.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.le_maxirtifa_2.setObjectName("le_maxirtifa_2")
        self.lbl_minirtifa_2 = QtWidgets.QLabel(self.gp_guvenlikonlemleri_2)
        self.lbl_minirtifa_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.lbl_minirtifa_2.setFont(font)
        self.lbl_minirtifa_2.setObjectName("lbl_minirtifa_2")
        self.le_minirtifa_2 = QtWidgets.QLineEdit(self.gp_guvenlikonlemleri_2)
        self.le_minirtifa_2.setGeometry(QtCore.QRect(10, 110, 113, 23))
        self.le_minirtifa_2.setObjectName("le_minirtifa_2")
        self.lbl_ortalamahiz_2 = QtWidgets.QLabel(self.gp_guvenlikonlemleri_2)
        self.lbl_ortalamahiz_2.setGeometry(QtCore.QRect(10, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.lbl_ortalamahiz_2.setFont(font)
        self.lbl_ortalamahiz_2.setObjectName("lbl_ortalamahiz_2")
        self.le_ortalamahiz_2 = QtWidgets.QLineEdit(self.gp_guvenlikonlemleri_2)
        self.le_ortalamahiz_2.setGeometry(QtCore.QRect(10, 160, 113, 23))
        self.le_ortalamahiz_2.setObjectName("le_ortalamahiz_2")
        self.gp_kamikaze_2 = QtWidgets.QGroupBox(self.tab_2)
        self.gp_kamikaze_2.setGeometry(QtCore.QRect(20, 300, 171, 191))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.gp_kamikaze_2.setFont(font)
        self.gp_kamikaze_2.setObjectName("gp_kamikaze_2")
        self.lbl_dalisacisi_2 = QtWidgets.QLabel(self.gp_kamikaze_2)
        self.lbl_dalisacisi_2.setGeometry(QtCore.QRect(10, 20, 81, 51))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(8)
        self.lbl_dalisacisi_2.setFont(font)
        self.lbl_dalisacisi_2.setObjectName("lbl_dalisacisi_2")
        self.le_dalisacisi_2 = QtWidgets.QLineEdit(self.gp_kamikaze_2)
        self.le_dalisacisi_2.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.le_dalisacisi_2.setObjectName("le_dalisacisi_2")
        self.lbl_dalisirtifasi_2 = QtWidgets.QLabel(self.gp_kamikaze_2)
        self.lbl_dalisirtifasi_2.setGeometry(QtCore.QRect(10, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.lbl_dalisirtifasi_2.setFont(font)
        self.lbl_dalisirtifasi_2.setObjectName("lbl_dalisirtifasi_2")
        self.le_dalisirtifasi_2 = QtWidgets.QLineEdit(self.gp_kamikaze_2)
        self.le_dalisirtifasi_2.setGeometry(QtCore.QRect(10, 110, 113, 23))
        self.le_dalisirtifasi_2.setObjectName("le_dalisirtifasi_2")
        self.lbl_yaklasmamesafesi_2 = QtWidgets.QLabel(self.gp_kamikaze_2)
        self.lbl_yaklasmamesafesi_2.setGeometry(QtCore.QRect(10, 140, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.lbl_yaklasmamesafesi_2.setFont(font)
        self.lbl_yaklasmamesafesi_2.setObjectName("lbl_yaklasmamesafesi_2")
        self.le_yaklasmamesafesi_2 = QtWidgets.QLineEdit(self.gp_kamikaze_2)
        self.le_yaklasmamesafesi_2.setGeometry(QtCore.QRect(10, 160, 113, 23))
        self.le_yaklasmamesafesi_2.setObjectName("le_yaklasmamesafesi_2")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 490, 181, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 60, 113, 22))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_31 = QtWidgets.QLabel(self.groupBox_11)
        self.label_31.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_11)
        self.label_32.setGeometry(QtCore.QRect(10, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 110, 113, 22))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(510, 90, 311, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_33 = QtWidgets.QLabel(self.groupBox_12)
        self.label_33.setGeometry(QtCore.QRect(0, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 140, 201, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_34 = QtWidgets.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(10, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 180, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 220, 301, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 260, 301, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.telemetri_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.telemetri_2.setGeometry(QtCore.QRect(20, 70, 281, 41))
        self.telemetri_2.setObjectName("telemetri_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(200, 90, 301, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.ip_adres_1 = QtWidgets.QLineEdit(self.groupBox_10)
        self.ip_adres_1.setGeometry(QtCore.QRect(10, 60, 113, 22))
        self.ip_adres_1.setText("")
        self.ip_adres_1.setObjectName("ip_adres_1")
        self.label_29 = QtWidgets.QLabel(self.groupBox_10)
        self.label_29.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setGeometry(QtCore.QRect(10, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.port_1 = QtWidgets.QLineEdit(self.groupBox_10)
        self.port_1.setGeometry(QtCore.QRect(10, 110, 113, 22))
        self.port_1.setText("")
        self.port_1.setObjectName("port_1")
        self.pb_server = QtWidgets.QPushButton(self.groupBox_10)
        self.pb_server.setGeometry(QtCore.QRect(160, 80, 121, 31))
        self.pb_server.setObjectName("pb_server")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(200, 300, 301, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.ip_adres_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.ip_adres_3.setGeometry(QtCore.QRect(10, 60, 113, 22))
        self.ip_adres_3.setText("")
        self.ip_adres_3.setObjectName("ip_adres_3")
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setGeometry(QtCore.QRect(10, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.port_3 = QtWidgets.QLineEdit(self.groupBox_8)
        self.port_3.setGeometry(QtCore.QRect(10, 110, 113, 22))
        self.port_3.setText("")
        self.port_3.setObjectName("port_3")
        self.cb_baglantituru_4 = QtWidgets.QComboBox(self.groupBox_8)
        self.cb_baglantituru_4.setEnabled(True)
        self.cb_baglantituru_4.setGeometry(QtCore.QRect(160, 60, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_baglantituru_4.sizePolicy().hasHeightForWidth())
        self.cb_baglantituru_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cb_baglantituru_4.setFont(font)
        self.cb_baglantituru_4.setToolTip("")
        self.cb_baglantituru_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_baglantituru_4.setObjectName("cb_baglantituru_4")
        self.cb_baglantituru_4.addItem("")
        self.cb_baglantituru_4.addItem("")
        self.cb_baglantituru_4.addItem("")
        self.cb_bantgenisligi_4 = QtWidgets.QComboBox(self.groupBox_8)
        self.cb_bantgenisligi_4.setEnabled(True)
        self.cb_bantgenisligi_4.setGeometry(QtCore.QRect(160, 110, 132, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_bantgenisligi_4.sizePolicy().hasHeightForWidth())
        self.cb_bantgenisligi_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cb_bantgenisligi_4.setFont(font)
        self.cb_bantgenisligi_4.setToolTip("")
        self.cb_bantgenisligi_4.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_bantgenisligi_4.setObjectName("cb_bantgenisligi_4")
        self.cb_bantgenisligi_4.addItem("")
        self.cb_bantgenisligi_4.addItem("")
        self.cb_bantgenisligi_4.addItem("")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(-30, 220, 481, 321))
        self.groupBox_9.setObjectName("groupBox_9")
        self.tw_menu.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 1331, 821))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.vl_map_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vl_map_1.setContentsMargins(0, 0, 0, 0)
        self.vl_map_1.setObjectName("vl_map_1")
        self.tw_menu.addTab(self.tab_4, "")
        self.lbl_clock = QtWidgets.QLabel(self.centralwidget)
        self.lbl_clock.setGeometry(QtCore.QRect(1040, -20, 181, 21))
        self.lbl_clock.setText("")
        self.lbl_clock.setObjectName("lbl_clock")
        self.bt_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.bt_minimize.setGeometry(QtCore.QRect(1450, 0, 31, 31))
        self.bt_minimize.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        image: url(icons/minimize.png);\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #dcdcdc;\n"
"        border-radius: 4px;\n"
"    }")
        self.bt_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimize.setIcon(icon)
        self.bt_minimize.setObjectName("bt_minimize")
        self.bt_maximize = QtWidgets.QPushButton(self.centralwidget)
        self.bt_maximize.setGeometry(QtCore.QRect(1480, 0, 31, 31))
        self.bt_maximize.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        image: url(icons/fullscreen.png);\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #4da6ff;\n"
"        border-radius: 4px;\n"
"    }")
        self.bt_maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/window/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximize.setIcon(icon1)
        self.bt_maximize.setObjectName("bt_maximize")
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        self.bt_close.setGeometry(QtCore.QRect(1510, 0, 41, 31))
        self.bt_close.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        image: url(icons/exit.png);\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #ff4d4d;\n"
"        border-radius: 4px;\n"
"    }")
        self.bt_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/window/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon2)
        self.bt_close.setObjectName("bt_close")
        self.bt_baglan = QtWidgets.QPushButton(self.centralwidget)
        self.bt_baglan.setGeometry(QtCore.QRect(1320, 0, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_baglan.sizePolicy().hasHeightForWidth())
        self.bt_baglan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_baglan.setFont(font)
        self.bt_baglan.setStyleSheet("QPushButton {\n"
"    box-shadow:inset 0px 1px 0px 0px #f29c93;\n"
"    background:linear-gradient(to bottom, #fe1a00 5%, #ce0100 100%);\n"
"    background-color: rgb(54, 161, 30);\n"
"    border-radius:6px;\n"
"    border:1px solid rgb(54, 161, 30);\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Ubuntu;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #b23e35;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #ce0100 5%, #fe1a00 100%);\n"
"    background-color: rgb(54, 141, 30);\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.bt_baglan.setFlat(False)
        self.bt_baglan.setObjectName("bt_baglan")
        self.cb_baglantituru = QtWidgets.QComboBox(self.centralwidget)
        self.cb_baglantituru.setEnabled(True)
        self.cb_baglantituru.setGeometry(QtCore.QRect(1050, 0, 261, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_baglantituru.sizePolicy().hasHeightForWidth())
        self.cb_baglantituru.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cb_baglantituru.setFont(font)
        self.cb_baglantituru.setToolTip("")
        self.cb_baglantituru.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"  selection-color: black;\n"
"  selection-background-color:rgb(14, 139, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"")
        self.cb_baglantituru.setObjectName("cb_baglantituru")
        self.cb_baglantituru.addItem("")
        self.cb_baglantituru.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(940, 0, 101, 20))
        self.checkBox.setObjectName("checkBox")
        Taslak.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Taslak)
        self.statusBar.setObjectName("statusBar")
        Taslak.setStatusBar(self.statusBar)

        self.retranslateUi(Taslak)
        self.tw_menu.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Taslak)

    def retranslateUi(self, Taslak):
        _translate = QtCore.QCoreApplication.translate
        self.pb_kac.setText(_translate("Taslak", "KAÇ"))
        self.gb_imuInfo.setTitle(_translate("Taslak", "IMU Verileri"))
        self.lbl_pitch.setText(_translate("Taslak", "-8.0"))
        self.lbl_yaw.setText(_translate("Taslak", "127.0"))
        self.label_3.setText(_translate("Taslak", "Roll (deg)"))
        self.label_5.setText(_translate("Taslak", "Yaw (deg)"))
        self.lbl_roll.setText(_translate("Taslak", "19.0"))
        self.label_4.setText(_translate("Taslak", "Pitch (deg)"))
        self.gb_gpsInfo.setTitle(_translate("Taslak", "GPS"))
        self.label_2.setText(_translate("Taslak", "Enlem"))
        self.label_6.setText(_translate("Taslak", "Boylam"))
        self.lbl_enlem.setText(_translate("Taslak", "40.744"))
        self.lbl_irtifa.setText(_translate("Taslak", "36.0"))
        self.lbl_boylam.setText(_translate("Taslak", "29.9435"))
        self.label_7.setText(_translate("Taslak", "İrtifa (m)"))
        self.pb_arm.setText(_translate("Taslak", "ARM"))
        self.cb_ucus_mod.setCurrentText(_translate("Taslak", "STABILIZED"))
        self.cb_ucus_mod.setItemText(0, _translate("Taslak", "STABILIZED"))
        self.cb_ucus_mod.setItemText(1, _translate("Taslak", "LAND"))
        self.cb_ucus_mod.setItemText(2, _translate("Taslak", "MISSION"))
        self.cb_ucus_mod.setItemText(3, _translate("Taslak", "HOLD"))
        self.cb_ucus_mod.setItemText(4, _translate("Taslak", "MANUAL"))
        self.cb_ucus_mod.setItemText(5, _translate("Taslak", "OFFBOARD"))
        self.gb_teaminfo.setTitle(_translate("Taslak", "TAKIP EDİLEN İHA VERİLERİ"))
        self.lbl_speed_r.setText(_translate("Taslak", "14.23"))
        self.label_12.setText(_translate("Taslak", "<html><head/><body><p>Hedef İha Hızı </p></body></html>"))
        self.lbl_pitch_r.setText(_translate("Taslak", "0.1"))
        self.lbl_yaw_r.setText(_translate("Taslak", "0.2"))
        self.label_8.setText(_translate("Taslak", "Roll (deg)"))
        self.label_9.setText(_translate("Taslak", "Yaw (deg)"))
        self.lbl_roll_r.setText(_translate("Taslak", "0.3"))
        self.label_22.setText(_translate("Taslak", "Pitch (deg)"))
        self.label_21.setText(_translate("Taslak", "Enlem"))
        self.label_23.setText(_translate("Taslak", "Boylam"))
        self.lbl_enlem_r.setText(_translate("Taslak", "40.742"))
        self.lbl_irtifa_r.setText(_translate("Taslak", "44.0"))
        self.lbl_boylam_r.setText(_translate("Taslak", "29.942"))
        self.label_24.setText(_translate("Taslak", "İrtifa (m)"))
        self.label_26.setText(_translate("Taslak", "Sunucu Saati"))
        self.label_25.setText(_translate("Taslak", "Zaman Farkı"))
        self.lbl_servertime.setText(_translate("Taslak", "11.38.38.739"))
        self.lbl_time_dif.setText(_translate("Taslak", "467"))
        self.pb_mod_onay.setText(_translate("Taslak", "Modu Onayla"))
        self.label_10.setText(_translate("Taslak", "<html><head/><body><p>Yer Hızı (m/s)</p></body></html>"))
        self.lbl_yerhizi.setText(_translate("Taslak", "15.23"))
        self.label_11.setText(_translate("Taslak", "Hava Hızı (m/s)"))
        self.lbl_havahizi.setText(_translate("Taslak", "12.78"))
        self.label_58.setText(_translate("Taslak", "<html><head/><body><p>Uçuş Modu</p></body></html>"))
        self.lbl_ucus_mod.setText(_translate("Taslak", "Stabilized"))
        self.label_59.setText(_translate("Taslak", "Uçuş Süresi"))
        self.lbl_ucus_zaman.setText(_translate("Taslak", "38.25"))
        self.pb_kill.setText(_translate("Taslak", "Kill"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.anamanu), _translate("Taslak", "ANA MENU"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_3), _translate("Taslak", "TAKIM VERILERI"))
        self.pb_renkmod.setText(_translate("Taslak", "Renk Körü Modu"))
        self.gp_guvenlikonlemleri_2.setTitle(_translate("Taslak", "GÜVENLİK ÖNLEMLERİ"))
        self.lbl_maxirtifa_2.setText(_translate("Taslak", "MAXİRTİFA"))
        self.lbl_minirtifa_2.setText(_translate("Taslak", "MİNİRTİFA"))
        self.lbl_ortalamahiz_2.setText(_translate("Taslak", "ORTALAMA HIZ"))
        self.gp_kamikaze_2.setTitle(_translate("Taslak", "KAMİKAZE"))
        self.lbl_dalisacisi_2.setText(_translate("Taslak", "DALIŞ AÇISI"))
        self.lbl_dalisirtifasi_2.setText(_translate("Taslak", "DALIŞ İRTİFASI"))
        self.lbl_yaklasmamesafesi_2.setText(_translate("Taslak", "YAKLAŞMA MESAFESİ"))
        self.groupBox_11.setTitle(_translate("Taslak", "KAMERA BAĞLANTISI"))
        self.label_31.setText(_translate("Taslak", "IP ADRESİ"))
        self.label_32.setText(_translate("Taslak", "PORT"))
        self.groupBox_12.setTitle(_translate("Taslak", "TEKNOFEST TELEMETRİ"))
        self.label_33.setText(_translate("Taslak", "Kullanici Adi : "))
        self.label_34.setText(_translate("Taslak", "Sifre :"))
        self.pushButton_5.setText(_translate("Taslak", "GIRIS"))
        self.pushButton_6.setText(_translate("Taslak", "CIKIS"))
        self.label_35.setText(_translate("Taslak", "Http:"))
        self.groupBox_10.setTitle(_translate("Taslak", "SADECE ARAYÜZ BAĞLANTI"))
        self.label_29.setText(_translate("Taslak", "IP ADRESİ"))
        self.label_30.setText(_translate("Taslak", "PORT"))
        self.pb_server.setText(_translate("Taslak", "GIRIS"))
        self.groupBox_8.setTitle(_translate("Taslak", "QROUNDCONTROL İLE BAĞLANTI"))
        self.label_27.setText(_translate("Taslak", "IP ADRESİ"))
        self.label_28.setText(_translate("Taslak", "PORT"))
        self.cb_baglantituru_4.setCurrentText(_translate("Taslak", "Bağlantı Türü", "asdsad"))
        self.cb_baglantituru_4.setItemText(0, _translate("Taslak", "Bağlantı Türü"))
        self.cb_baglantituru_4.setItemText(1, _translate("Taslak", "TCP"))
        self.cb_baglantituru_4.setItemText(2, _translate("Taslak", "udp"))
        self.cb_bantgenisligi_4.setCurrentText(_translate("Taslak", "Bant Genişliği", "asdsad"))
        self.cb_bantgenisligi_4.setItemText(0, _translate("Taslak", "Bant Genişliği"))
        self.cb_bantgenisligi_4.setItemText(1, _translate("Taslak", "57600"))
        self.cb_bantgenisligi_4.setItemText(2, _translate("Taslak", "115200"))
        self.groupBox_9.setTitle(_translate("Taslak", "GroupBox"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_2), _translate("Taslak", "AYARLAR"))
        self.tw_menu.setTabText(self.tw_menu.indexOf(self.tab_4), _translate("Taslak", "GÖREV"))
        self.bt_baglan.setText(_translate("Taslak", "Bağlan"))
        self.cb_baglantituru.setCurrentText(_translate("Taslak", "QROUND CONTROL VE ARAYÜZ", "asdsad"))
        self.cb_baglantituru.setItemText(0, _translate("Taslak", "QROUND CONTROL VE ARAYÜZ"))
        self.cb_baglantituru.setItemText(1, _translate("Taslak", "SADECE ARAYÜZ"))
        self.checkBox.setText(_translate("Taslak", "Simülasyon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Taslak = QtWidgets.QMainWindow()
    ui = Ui_Taslak()
    ui.setupUi(Taslak)
    Taslak.show()
    sys.exit(app.exec_())
